fix: arreglo de test y ampliación
ISPP-23-24-Grupo-3/musclemate-backend pull request #132
Opened 2024-03-12 19:47 UTC by Leonidas6000

#131

2024-03-13 20:24 UTC, agudevbon requested changes
Tras ejecutar los tests en local encuentro que muchos fallan, por favor arreglar los tests antes de hacer merge

2024-03-14 11:27 UTC, Leonidas6000 reviewed
El error esta en el nombre de la pull request ya que realmente queria decir arreglo de test de event y ampliacion, no de todos solo de event

2024-03-14 11:35 UTC, manvazmar3 approved these changes

2024-03-14 11:53 UTC, agudevbon approved these changes

2024-03-14 11:53 UTC, merged